### ISSUE TITLE
Media Directories Cannot be Added

### ISSUE THREAD

**Issue by Legendsmith** [Borewit/listFix#15]
Like it says on the tin, I try to add a media directory and it does not actually add it. No error message or anything.
~~The only thing I can possibly consider is that the media directories I'm trying to add are not on my C;/ drive; I keep my music collection on a different hard drive.~~ Nope it won't add C;/ drive dirs.
Specs: `Windows 10 Pro 19042.1466`

**Comment by midmarch** [comment]
Are you sure it is not added? It should just list the diretcory as an entry, not the content.
 It will list the content of your playlist.

**Comment by Borewit** [comment]
I assume you mean `C:\`.
Hmm, weird, I works for me, takes long though to scan my entire HDD. Using Windows 10 Pro as well.

**Comment by touwys** [comment]
I simply have to say how absolutely delighted I am to have discovered this particular release of list Fix, after the abandonment of the original, now more than a decade ago. Thank you, @Borewit, for reviving it!

Sadly, I have to report that — on my PC — it still suffers from the same malady as the issue from 2022 under this topic, namely that the app will not add the Media Directories required to function properly. Once I clicked to add the Media Directory, I waited several hours for the directory to get displayed, but none eventually did. I repeated this step was several times over different days. The media directories are housed on a 6 TB internal hard drive, and the app on an SSD-drive. ListFix does not appear to hang during this process. Also, there is no progress bar in display to provide the usual visuals of the progress — although I am not sure if such a facility is available.

ListFix is installed in the C:/programme directory on a PC equipped with Windows 7 x64 Ultimate. This also raises a question: can listFix be installed as a portable app, too? If so, what needs to be done to achieve this?

I am quite willing to go the extra mile to provide more information where needed to track down this issue.

A screenshot is provided for what it's worth.

Thank you.

•
•

![listFix media directory not added](https://user-images.githubusercontent.com/65730626/211779402-e2c836b2-9d63-4f3a-b693-e1cba7765bac.gif)

**Comment by Borewit** [comment]
I have limited time available, so I have to pick my battles. I thought it was a nice app, therefor I spend quite a lot of time porting the development environment to Github. I had hoped it would be picked by the open source community, but there is overall very little interest in.

**Comment by touwys** [comment]
Thank you for your response @Borewit.

Are we to assume that you are abandoning the project?

The poor demand for it is probably only due to lack of public awareness of its existence. For one, I accidentally stumbled upon it by accident. It works so incredibly well that it quickly became an indispensable tool to my media library. When it sadly failed to add the Media Library directories, the original developer turned unresponsive to pleas requesting for help. I sincerely hope that you will not completely give up on the project, since we have nowhere else to turn if you do. Can you at least take a good look at the code again to see if you can find something out of the ordinary? Is there anywhere else we turn or other recommendations you may have?



----------------------------------------

12 Jan 2023 01:20:24 Borewit ***@***.***>:

**Comment by Borewit** [comment]
I loaded the project and started listFix() in my development environment.

This time I run in issues loading when selecting a media file myself.
The quality of the code in general very poor.
Exceptions are caught and most of the time ignored, which makes it difficult to find of what the original cause is.

I had the impression the issue I run into was errors caused when parsing the `.ini` holding the application settings.
These are stored in `%HOMEPATH%\.listFix()`.

You could try to delete those and give it another try.

I started to rewrite the code, and replace the buggy ini-parsers with more modern JSON serialization and deserialization on the [migrate-appconfig-to-json branch](https://github.com/Borewit/listFix/tree/migrate-appconfig-to-json).

Quite a lot of work my friend. It's like renovating an old house, you try to fix one thing and the next thing false apart.

**Comment by touwys** [comment]
Thank you @Borewit, I truly appreciate that you took another look to see what the underlying cause might be. I will try your proposed deletion of the app ini-file, and report the result.

I am also sorry to learn about the poor code, and the effort required of you to fix it. Hopefully, you will get renewed courage to proceed to fix it, regardless. Your metaphor about the old house in need of renovation is a vivid one, which I thoroughly understand and symphatise with — if only because I live in one that fits your description, exactly! 😁

As an aside, can listFix() be installed as a portable app?

----------------------------------------

12 Jan 2023 23:48:14 Borewit ***@***.***>:

**Comment by touwys** [comment]
> I had the impression the issue I run into was errors caused when parsing the `.ini` holding the application settings. These are stored in `%HOMEPATH%\.listFix()`.
> 
> You could try to delete those and give it another try.

I followed your recommendation, which, unfortunately, did not alleviate the issue. I then proceeded to do a fresh installation of listFix(), but it behaved the same as before:

Something of note, perhaps: With the fresh installation, I started out by adding one playlist, which it did just fine. Then, I opened the Options to set the Playlist Directory populated by my current playlists, but listFix() became unresponsive/hanged indefinitely. Upon restart, I tried to add the Media Directory, but it did not do anything— although this time, listFix() remained responsive.

Is there anything you can think of that might be worth trying?
•

**Comment by Borewit** [comment]
> As an aside, can listFix() be installed as a portable app?

I don't see many technical limitations to do that. I have no experience how to wrap a portable app nicely.

I see so many potential problems, and errors which are kept hidden under the carpet. Some logging could help what your exact problem is. Please start with trying this development version https://github.com/Borewit/listFix/pull/19#issuecomment-1382221807.

**Comment by touwys** [comment]
@Borewit, I cannot thank you enough for having decided to give it another go. Please see my comments at #19.

As far as the portable version is concerned, unessential.

----------------------------------------

13 Jan 2023 20:28:44 Borewit ***@***.***>:

**Comment by Borewit** [comment]
I am going to do things in a few smaller steps. I suspect you have run into [this issue (#24)](https://github.com/Borewit/listFix/issues/24), and I will do the very minimum to code first trying to address that. Lot of work to even be able to build the code, as dependencies have changed (also vanished / now behave differently).

**Comment by touwys** [comment]
Thank you for what you are doing. I have noticed a flourish of listFix() activity from you lately, and I trust you to figure out the solutions as you see fit. 

Please note that I have only very basic knowledge about the GitHub-site processes, and the developer language generally in use, so that I am really adrift when it comes to keeping track, and making sense of, project developments. So, please let me know when you expect of me to do something to advance the project?

**Comment by Borewit** [comment]
> So, please let me know when you expect of me to do something to advance the project?

If you can help me testing to would be awesome. I will try keep things easy for you. I am now able to build the installers again. 

I just released [listFix() 2.4.1](https://github.com/Borewit/listFix/releases/tag/2.4.1) with just some small changes compared to the previous release. If you can let me know how that one works, that would be great @touwys.

**Comment by Borewit** [comment]
Same as issue #24 

Reported as being resolved in [v2.4.2](https://github.com/Borewit/listFix/releases/tag/v2.4.2) as reported https://github.com/Borewit/listFix/pull/19#issuecomment-1383740584.
