### ISSUE TITLE
Anomaly: a manually repaired track, once saved, gets replaced by the next repair

### ISSUE THREAD

**Issue by touwys** [Borewit/listFix#194]
**listFix() v2.8.0**

Location is the Playlist Editor, in which there is open a 24-track playlist. The 24 tracks are all up for repair (finding matches).

**Steps:**

1. Click the magic wand on the toolbar to start the auto repair for all of 24 tracks.

2. Immediately, after having it detect all the _exact_ matches, _cancel_ the "Select Closest Matches" dialogue still in progress. Accordingly, it should not proceed with next trying to detect the _closest matches_.

3. Click on the diskette button on the toolbar, in order to save this first round—the _exact_ repairs—to the playlist.

4. Next, select _one_ "file name" (i.e. track)—starting with the _first one_ in the playlist—for which a matching track is to be found. Right-click on it.

5. In the context menu presented, choose "Repair Playlist". 

6. Select "OK" for the first (any?) match found.

7. Upon return to the playlist, after clicking OK, save the playlist.

8. Select the _very next_ (any?) track in the playlist for which a matching track is to be found. Right-click on it.

9. In the context menu presented, choose "Repair Playlist". 

10. Select "OK" for the first (any?) match found.

11. Upon return to the playlist, after clicking OK, save the playlist.

**Issues:**

The track that got repaired first, and was saved, gets summarily replaced by the second track that got repaired. However, the second, _unrepaired_ track still also remains in position in the playlist, thus keeping the total number of tracks in the playlist at 24.

—

**Comment by touwys** [comment]
**Additional information pertaining to listFix 2.8.0 & 2.8.0-7**

1. After Step 3 above, having saved the first round of repairs (i.e. the exact matches) the corresponding matches in the playlist are marked with an "OK" icon to reflect its current status.

![image](https://github.com/Borewit/listFix/assets/65730626/cb6a1bb0-239f-4a57-b92a-1e5663c0e785)

2. If one should now proceed to next find the closest matches for the remaining tracks, the "OK" icon for the exact matches already found, is summarily replaced by a checkmark. An unnecessary duplication? Saved matches should remain saved, should it not, and the process to find the closest matches should only be applicable to the remainder of the tracks in need of repair.

![image](https://github.com/Borewit/listFix/assets/65730626/bc1a3263-aaf3-448c-9dbe-f94a9deed717)

**Comment by Borewit** [comment]
Please note 2.8.0-7 is not a unique version number, but I assume that is taken from PR #199. 7 is the commit distances (read the number of changes) since 2.8.0. Another branch can have the same commit distance. 

What is unique is the commit number "3ac7249016bbc8a8c45679efb9152e7d12584515" which identifies the last change on after which the build was started.  If I write the exact same code without quotes, Github understands that code as well, and will turn it into a link pointing that exact unique code change: 3ac7249016bbc8a8c45679efb9152e7d12584515

As it so long, and so super unique it will only show the first 7 hexadecimal. The change on a duplication in just those 7 hexadecimals is already 1 on 7^16, if the code is change history is different. 
So that code actually represent the entire history of the project, only when you repeat the exact same changes, by the exact same developer, you will end of with this exact same code. This is what we nowadays call blockchain technology.

I can add that to the version number if you prefer, e.g. 2.8.0-7-3ac7249.

**Comment by touwys** [comment]
> I can add that to the version number if you prefer, e.g. 2.8.0-7-3ac7249.

It's fine the way it is, thanks. :)

**Comment by Borewit** [comment]
Resolved by #201
